import type { NextPage } from 'next';
import Head from 'next/head';
import Pool from './pool/index';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <Pool />
    </>
  );
};

export default Home;
